# Generated by Django 4.2 on 2025-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, verbose_name='用户昵称'),
            preserve_default=False,
        ),
    ]
