# Generated by Django 4.2 on 2024-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='openaikey',
            table='openai_key',
        ),
    ]
