# Generated by Django 4.2 on 2024-12-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0002_alter_openaikey_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='quota',
            field=models.FloatField(default=0, verbose_name='总额度'),
        ),
        migrations.AddField(
            model_name='openaikey',
            name='remaining_balance',
            field=models.FloatField(default=0, editable=False, verbose_name='剩余额度'),
        ),
        migrations.AddField(
            model_name='openaikey',
            name='usage',
            field=models.FloatField(default=0, verbose_name='已使用额度'),
        ),
    ]
