# Generated by Django 4.2 on 2024-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0003_openaikey_quota_openaikey_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='api_type',
            field=models.CharField(default='', verbose_name='API类型'),
            preserve_default=False,
        ),
    ]
