# Generated by Django 4.2 on 2025-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0004_openaikey_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='状态')),
                ('code', models.CharField(unique=True, verbose_name='API TOKEN')),
                ('api_type', models.CharField(verbose_name='API类型')),
                ('quota', models.FloatField(default=0, verbose_name='总额度')),
                ('usage', models.FloatField(default=0, verbose_name='已使用额度')),
                ('remaining_balance', models.FloatField(default=0, editable=False, verbose_name='剩余额度')),
            ],
            options={
                'verbose_name': 'Openai Token',
                'verbose_name_plural': 'Openai Token',
                'db_table': 'openai_token',
            },
        ),
        migrations.DeleteModel(
            name='OpenAiKey',
        ),
    ]
