# Generated by Django 4.2 on 2025-01-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0005_openaitoken_delete_openaikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openaitoken',
            old_name='remaining_balance',
            new_name='remain_quota',
        ),
        migrations.RenameField(
            model_name='openaitoken',
            old_name='usage',
            new_name='used_quota',
        ),
    ]
