# Generated by Django 4.2 on 2025-01-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openai', '0006_rename_remaining_balance_openaitoken_remain_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaitoken',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openaitoken',
            name='create_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='openaitoken',
            name='write_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AddField(
            model_name='openaitoken',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tokens', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
