# Generated by Django 4.2 on 2025-01-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openai', '0007_openaitoken_create_date_openaitoken_create_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaitoken',
            name='create_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='openaitoken',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
