# Generated by Django 4.2 on 2025-01-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0008_alter_openaitoken_create_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaitoken',
            name='create_uid',
        ),
        migrations.RemoveField(
            model_name='openaitoken',
            name='write_uid',
        ),
    ]
